version: '3.1'

services:

  postgres-service:
    container_name: ebank-postgres
    image: postgres:13.2
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb-service:
    container_name: ebank-mongo
    image: mongo
    ports:
      - "27017:27017"

  zookeeper:
    container_name: ebank-zookeeper
    image: strimzi/kafka:0.20.0-kafka-2.5.1
    command: [
      "sh" , "-c" ,
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    container_name: ebank-kafka
    image: strimzi/kafka:0.20.0-kafka-2.5.1
    command: [
      "sh" , "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9290
      KAFKA_LISTENERS: PLAINTEXT://localhost:9290
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
