apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: kong
  namespace: ebank-quarkus-cqrs
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: ebank-ingress


spec:
  rules:
    - http:
        paths:
          - path: /transaction-service/*
            pathType: Prefix
            backend:
              service:
                name: transaction-service
                port:
                  number: 8080
          - path: /balance-service/*
            backend:
              service:
                name: balance-service
                port:
                  number: 8080
