apiVersion: v1
kind: Service
metadata:
  name: ebank-balance-service
  namespace: ebank-quarkus-cqrs
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: ebank-balance-app
    namespace: ebank-quarkus-cqrs